import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/navbar'
import { useMemo, useState } from 'react'
import { useConnection, useWallet } from '@solana/wallet-adapter-react'
import { LAMPORTS_PER_SOL, Transaction, PublicKey } from '@solana/web3.js'
import { gql, useQuery } from '@apollo/client'
import client from '../client'
import {
  createAssociatedTokenAccountInstruction,
  getAssociatedTokenAddress,
  getOrCreateAssociatedTokenAccount,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createTransferInstruction
} from '@solana/spl-token'
import { NftCard } from '../components/nftCard'

const Home: NextPage = () => {
  const { publicKey, signTransaction } = useWallet()
  const { connection } = useConnection()

  const massSend = async (list: Nft[], to: string) => {
    if (!list || !to || !connection || !publicKey || !signTransaction) {
      console.log('returning')
      return
    }

    try {
      console.log("to: ", to)
      new PublicKey(to)
      console.log('valid dest address: ', to)
    } catch (e) {
      console.log(e.message)
      return
    }

    if (!list.length) {
      console.log('probably want to select some nfts')
      return
    }

    const tx = new Transaction()
    console.log("trying to send ", list.length, " nfts")
    for (var i = 0; i < list.length; i++) {
      const mintPublicKey = new PublicKey(list[i].mintAddress)
      const fromTokenAccount = await getAssociatedTokenAddress(
        mintPublicKey,
        publicKey
      )
      const fromPublicKey = publicKey
      const destPublicKey = new PublicKey(to)
      const destTokenAccount = await getAssociatedTokenAddress(
        mintPublicKey,
        destPublicKey
      )
      const receiverAccount = await connection.getAccountInfo(destTokenAccount)

      if (receiverAccount === null) {
        tx.add(
          createAssociatedTokenAccountInstruction(
            fromPublicKey,
            destTokenAccount,
            destPublicKey,
            mintPublicKey,
            TOKEN_PROGRAM_ID,
            ASSOCIATED_TOKEN_PROGRAM_ID
          )
        )
      }

      tx.add(
        createTransferInstruction(
          fromTokenAccount,
          destTokenAccount,
          fromPublicKey,
          1
        )
      )
    }
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash
    tx.feePayer = publicKey

    let signed: Transaction | undefined = undefined

    try {
      signed = await signTransaction(tx)
    } catch (e) {
      console.log(e.message)
      return
    }

    let signature: string | undefined = undefined

    try {
      signature = await connection.sendRawTransaction(signed.serialize())

      await connection.confirmTransaction(signature, 'confirmed')
    } catch (e) {
      console.log(e.message)
    }
  }

  const GET_NFTS = gql`
    query GetNfts($owners: [PublicKey!], $limit: Int!, $offset: Int!) {
      nfts(owners: $owners, limit: $limit, offset: $offset) {
        address
        mintAddress
        name
        description
        image
        owner {
          address
          associatedTokenAccountAddress
        }
      }
    }
  `

  interface Nft {
    name: string
    address: string
    description: string
    image: string
    mintAddress: string
  }

  const [nfts, setNfts] = useState<Nft[]>([])
  const [sending, setSending] = useState<Nft[]>([])
  const [to, setTo] = useState('')

  useMemo(() => {
    if (publicKey?.toBase58()) {
      client
        .query({
          query: GET_NFTS,
          variables: {
            owners: [publicKey?.toBase58()],
            offset: 0,
            limit: 200
          }
        })
        .then(res => setNfts(res.data.nfts))
    } else {
      setNfts([])
    }
  }, [publicKey?.toBase58()])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <div className='container'>
        <label htmlFor='my-modal-3' className='btn modal-button'>
          {sending.length}
        </label>
        <h1>Connected to: {publicKey?.toBase58()}</h1>
        <div className='grid grid-cols-4 gap-4'>
          {nfts.map(e => (
            <NftCard
              image={e.image}
              name={e.name}
              unselect={() => {
                console.log('removing')
                setSending(sending.filter(item => item !== e))
              }}
              select={() => {
                console.log('adding')
                setSending([...sending, e])
              }}
              selected={sending.includes(e)}
            />
          ))}

          <div>
            <button
              onClick={() => massSend(sending, to)}
              className='border border-black'
            >
              Send them
            </button>
          </div>
        </div>
      </div>

      <footer></footer>
      <input type='checkbox' id='my-modal-3' className='modal-toggle' />
      <div className='modal'>
        <div className='relative modal-box'>
          <label
            htmlFor='my-modal-3'
            className='absolute btn btn-sm btn-circle right-2 top-2'
          >
            ✕
          </label>
          <h3 className='text-lg font-bold'>Send the NFS</h3>
          <div>
            {sending.length === 0 && <h1>Select some nfts to send fren!</h1>}
            {sending.map(s => (
              <div className='flex flex-row mb-2 border border-white'>
                <img src={s.image} width={'75px'} />
                <p>{s.name}</p>
                <button
                  className='btn'
                  onClick={() => {
                    setSending(sending.filter(item => item !== s))
                  }}
                >
                  X
                </button>
              </div>
            ))}
            <h2>To send</h2>
            <input
              type='text'
              className=''
              placeholder='pubkey address'
              onChange={e => {
                setTo(e.target.value)
              }}
            />
            <button className='btn btn-primary' onClick={()=>{ massSend(sending, to) }}>🚀</button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
